apiVersion: v1
kind: Pod
metadata:
  name: website
spec:
  containers:
    - name: webserver
      image: httpd:latest
    - name: shell
      image: alpine:latest
      tty: true
      stdin: true
    - name: loop
      image: alpine:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do date; sleep 1; done"]
