---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: dockercoins
    component: rng
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: dockercoins
    component: hasher
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: dockercoins
    component: redis
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: dockercoins
    component: webui
---

