apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webui
spec:
  ingressClassName: nginx
  rules:
    - host: web.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webui
                port:
                  number: 80
