apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-db
spec:
  template:
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
          emptyDir: null
