apiVersion: v1
kind: Pod
metadata:
  name: timeserver
  labels:
    app: k8stime
    component: timeserver
spec:
  nodeName: xam-kube-17-2
  containers:
    - name: timeserver
      image: httpd:latest
      volumeMounts:
        - name: htdocs
          mountPath: /usr/local/apache2/htdocs
      readinessProbe:
        httpGet:
          port: 80
          path: /ready.txt
      livenessProbe:
        httpGet:
          port: 80
          path: /alive.txt
      startupProbe:
        httpGet:
          port: 80
          path: /started.txt
  volumes:
    - name: htdocs
      persistentVolumeClaim:
        claimName: pvc
